version: '3.7'

services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - loki

  loki:
    image: grafana/loki
    container_name: loki
    restart: unless-stopped
    command: -config.file=/etc/grafana-loki/loki/loki-config.yaml
    ports:
      - 3100:3100
    volumes:
      - ./loki:/etc/grafana-loki/loki
    networks:
      - loki

  promtail:
    image: grafana/promtail
    container_name: promtail
    restart: unless-stopped
    command: -config.file=/etc/grafana-loki/promtail/promtail-config.yaml
    volumes:
      - ./promtail:/etc/grafana-loki/promtail
      - /var/log:/var/log
    networks:
      - loki

networks:
  loki:
    name: loki

volumes:
  grafana-data:
    name: grafana-data
